const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function backend(){
 const sheets=new Map();function sheet(name){let s={rows:[],columns:name==='HiService_Stock_Counts'?6:(name==='HiService_Stock'?13:(name==='Timesheets'?14:10)),getMaxColumns(){return this.columns},insertColumnsAfter(at,n){this.columns+=n},getLastRow(){return this.rows.length},setFrozenRows(){},appendRow(r){this.rows.push([...r])},getRange(r,c,n=1,m=1){if(c+m-1>s.columns)throw Error('Range exceeds grid limits');let range={getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>s.rows[r+i-1]?.[c+j-1]??'')),setValues(v){v.forEach((row,i)=>{s.rows[r+i-1]??=[];row.forEach((x,j)=>s.rows[r+i-1][c+j-1]=x)});return range},setValue(v){return range.setValues([[v]])},setFormulas(v){return range.setValues(v)}};for(let k of ['setFontWeight','setBackground','setFontColor'])range[k]=()=>range;return range}};sheets.set(name,s);return s}
 const ss={getSheetByName:n=>sheets.get(n),insertSheet:sheet,getSpreadsheetTimeZone:()=> 'Africa/Johannesburg'};
 let c={Date,SpreadsheetApp:{getActiveSpreadsheet:()=>ss},Session:{getScriptTimeZone:()=> 'Africa/Johannesburg'},Utilities:{formatDate:(d,t,f)=>f==='yyyy-MM-dd'?'2026-10-04':'Sunday',getUuid:()=> 'fixture-uuid'},auth_:b=>({username:b.user||'worker',name:b.user==='admin'?'Admin':'Test Worker',role:b.user==='admin'?'Admin':'Worker'}),out_:x=>x,calc_:(d,a,b,l)=>/^\d\d:\d\d$/.test(a)&&/^\d\d:\d\d$/.test(b)?{normal:8,overtime:1,total:9}:null,shiftReviewReason_:()=> 'Invalid time',timeTxt_:x=>String(x),sheet_:n=>sheets.get(n),findEntry_:(w,d)=>{let i=sheets.get('Timesheets').rows.findIndex((r,i)=>i>0&&r[0]===d&&r[3]===w);return i<0?null:i+1},writeEntry_:(u,r)=>{let sh=sheets.get('Timesheets'),at=c.findEntry_(r.worker,r.date),row=[r.date,'Sunday','Sunday',r.worker,r.job||'',r.timeIn,r.timeOut,r.lunch,8,1,9,r.note||'',u.username,new Date()];if(at){sh.rows[at-1]=row;return {updated:true}}sh.appendRow(row);return {added:true}},rebuildWorkerTabs:()=>{}};
 vm.createContext(c);vm.runInContext(fs.readFileSync('google-apps-script/HiService.gs','utf8'),c);sheet('Timesheets').appendRow(Array(14).fill('header'));c.setupHiService();
 function add(code,name,store=10,van=0){sheets.get('HiService_Stock').appendRow([code,name,'Other','','each',10,store,van,0,0,'Yes','',''])}
 return {c,sheets,add,post:b=>c.hiServicePost_(b)};
}
test('invalid later movement line cannot partially change earlier items',()=>{let b=backend();b.add('A','Cable');b.add('B','Pipe',1);assert.throws(()=>b.post({action:'hiStockTransfer',from:'Stoor',to:'CEY 59799',lines:[{code:'A',qty:3},{code:'B',qty:2}]}),/only has/);assert.equal(b.sheets.get('HiService_Stock').rows[1][6],10);assert.equal(b.sheets.get('HiService_Stock_Movements').rows.length,1)});
test('same-place transfers and noninteger quantities are rejected before writes',()=>{let b=backend();b.add('A','Cable');for(let qty of [NaN,Infinity,null,'',true,1.5,-2])assert.throws(()=>b.post({action:'hiStockReceive',place:'Stoor',lines:[{code:'A',qty}]}));assert.throws(()=>b.post({action:'hiStockTransfer',from:'Stoor',to:'Stoor',lines:[{code:'A',qty:3}]}),/different/);assert.equal(b.sheets.get('HiService_Stock').rows[1][6],10)});
test('repeated item lines are aggregated and validated against their combined quantity',()=>{let b=backend();b.add('A','Cable',5);assert.throws(()=>b.post({action:'hiStockTransfer',from:'Stoor',to:'CEY 59799',lines:[{code:'A',qty:3},{code:'A',qty:3}]}),/only has/);let r=b.post({action:'hiStockReceive',place:'Stoor',lines:[{code:'A',qty:2},{code:'A',qty:3}]});assert.equal(r.result.changed,1);assert.equal(b.sheets.get('HiService_Stock').rows[1][6],10);assert.equal(b.sheets.get('HiService_Stock_Movements').rows[1][7],5)});
test('lost acknowledgement retry with same request ID does not receive stock twice',()=>{let b=backend();b.add('A','Cable');let request={action:'hiStockReceive',place:'Stoor',requestId:'req-1',lines:[{code:'A',qty:3}]};b.post(request);assert.equal(b.post(request).result.unchanged,true);assert.equal(b.sheets.get('HiService_Stock').rows[1][6],13);assert.equal(b.sheets.get('HiService_Stock_Movements').rows.length,2)});
test('duplicate codes remain rejected counts and cannot silently receive movement',()=>{let b=backend();b.add('A','Cable');b.add('A','Pipe');let r=b.post({action:'hiStockCount',place:'Stoor',counts:{A:2}});assert.deepEqual(Array.from(r.rejected),['A']);assert.equal(r.changed,0);assert.throws(()=>b.post({action:'hiStockReceive',place:'Stoor',lines:[{code:'A',qty:1}]}),/Duplicate/)});
test('blank/null/boolean counts never overwrite existing quantity with zero',()=>{for(let value of ['',null,true]){let b=backend();b.add('A','Cable');let r=b.post({action:'hiStockCount',place:'Stoor',counts:{A:value}});assert.deepEqual(Array.from(r.rejected),['A']);assert.equal(b.sheets.get('HiService_Stock').rows[1][6],10)}});
test('timesheet retries do not duplicate the day and workers cannot edit submitted hours or impersonate',()=>{let b=backend(),row={date:'2026-10-04',worker:'Test Worker',timeIn:'07:00',timeOut:'17:00',lunch:60};b.post({action:'hiTimesheet',row});assert.equal(b.post({action:'hiTimesheet',row}).result.unchanged,true);assert.equal(b.sheets.get('Timesheets').rows.length,2);assert.throws(()=>b.post({action:'hiTimesheet',row:{...row,timeOut:'18:00'}}),/locked/);assert.throws(()=>b.post({action:'hiTimesheet',row:{...row,worker:'Someone Else'}}),/own timesheet/);assert.throws(()=>b.post({action:'hiTimesheet',user:'admin',row:{...row,date:'2026-10-05'}}),/Future/)});

test('six-column existing count sheet expands before audit writes and old rows show unknown movement',()=>{let b=backend();b.add('A','Cable');let sh=b.sheets.get('HiService_Stock_Counts');sh.appendRow([new Date(),'worker','Stoor','A','Cable',4]);let old=b.c.hiDailyStockReport_('2026-10-04');assert.equal(old.counts[0].old,null);assert.equal(old.counts[0].delta,null);b.post({action:'hiStockCount',place:'Stoor',counts:{A:3}});assert.equal(sh.columns,8);assert.deepEqual(sh.rows[2].slice(5),[3,10,-7])});
