const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
test('calendar is a permission-gated module with a complete cached shell',()=>{const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');assert.match(html,/data-go="calendar"/);assert.match(html,/calendar:'calendar.view'/);assert.match(html,/if\(id==='calendar'\)loadHiCalendar\(\)/);for(const file of ['calendar.js','timetree-calendar.js','vendor/rrule.min.js']){assert.ok(html.includes('src="'+file+'"'));assert.ok(sw.includes('./'+file));assert.ok(fs.existsSync(file));new vm.Script(fs.readFileSync(file,'utf8'));}});
test('read-only calendar discards replies from a previous account',async()=>{let resolve;const pending=new Promise(r=>resolve=r),elements={};function $(id){return elements[id]||(elements[id]={textContent:'',innerHTML:'',classList:{add(){}},setAttribute(){},querySelectorAll:()=>[]});}const c={window:{},console,Intl,Date,JSON,Promise,Set,S:{url:'local',username:'first'},$,esc:String,hiCan:()=>true,apiGet:()=>pending,TimeTreeCalendar:{layout:()=>({html:'',errors:[]}),details:()=>''}};vm.createContext(c);c.loadHiCalendar=(...args)=>c.window.loadHiCalendar(...args);vm.runInContext(fs.readFileSync('calendar.js','utf8'),c);let p=c.window.loadHiCalendar();c.S.username='second';resolve({events:[],lastImportAt:'2026-10-07T00:00:00Z'});await p;assert.ok(!elements.hiCalMsg.textContent.includes('Last connector'));});
test('shared recurrence view retains notes and marks explicit archives without deleting source objects',()=>{global.rrule=require('../vendor/rrule.min.js');const view=require('../timetree-calendar.js'),event={id:'tt:1:a',source:'timetree',customer:'Test',date:'2026-10-07',startAt:Date.parse('2026-10-07T08:00:00Z'),endAt:Date.parse('2026-10-07T09:00:00Z'),timeZone:'Africa/Johannesburg',recurrences:[],notes:'Required cable',status:'ARCHIVED'};assert.equal(view.entries([event],'2026-10-01','2026-10-31').events.length,0);assert.equal(event.notes,'Required cable');assert.match(view.details(event),/Required cable/);});
test('reopening shares in-flight request, keeps cached bookings on failure, and refresh bypasses freshness',async()=>{
 const elements={};function $(id){return elements[id]||(elements[id]={textContent:'',innerHTML:'',classList:{add(){}},setAttribute(){},querySelectorAll:()=>[]});}
 let calls=0,resolve,fail=false;const deferred=new Promise(r=>resolve=r),renders=[];
 const c={window:{},console,Intl,Date,JSON,Promise,Set,S:{url:'fixture',username:'first'},$,hiCan:()=>true,apiGet:()=>{calls++;return fail?Promise.reject(Error('offline')):deferred;},TimeTreeCalendar:{layout:events=>{renders.push(events.length);return {html:'',errors:[]}},details:()=>''}};
 vm.createContext(c);c.loadHiCalendar=(...args)=>c.window.loadHiCalendar(...args);vm.runInContext(fs.readFileSync('calendar.js','utf8'),c);
 const a=c.window.loadHiCalendar(),b=c.window.loadHiCalendar();assert.equal(calls,1);resolve({events:[{id:'one'}],lastImportAt:'2026-10-07T00:00:00Z'});await Promise.all([a,b]);await c.window.loadHiCalendar();assert.equal(calls,1);assert.equal(renders.at(-1),1);
 fail=true;await c.window.loadHiCalendar(true);assert.equal(calls,2);assert.equal(renders.at(-1),1);assert.match(elements.hiCalMsg.textContent,/Showing saved bookings/);
});
test('agenda and month show multi-day bookings, empty state and escaped customer text',()=>{
 const view=require('../timetree-calendar.js');const e={id:'fixture',source:'timetree',customer:'<img src=x>',startAt:Date.parse('2026-10-07T08:00:00Z'),endAt:Date.parse('2026-10-08T09:00:00Z'),timeZone:'Africa/Johannesburg',recurrences:[],startTime:'10:00',endTime:'11:00'};
 const agenda=view.layout([e],new Date(2026,9,7),'agenda','data-hi-event');assert.equal((agenda.html.match(/data-hi-event/g)||[]).length,2);assert.ok(!agenda.html.includes('<img'));assert.match(agenda.html,/&lt;img/);
 const grid=view.layout([e],new Date(2026,9,7),'month','data-hi-event');assert.equal((grid.html.match(/class="cal-day/g)||[]).length,42);assert.match(view.layout([],new Date(),'agenda','data-hi-event').html,/No bookings/);
});
